/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpsRouteImport } from './routes/vps'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as CloudVpsRouteImport } from './routes/cloud-vps'
import { Route as IndexRouteImport } from './routes/index'

const VpsRoute = VpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudVpsRoute = CloudVpsRouteImport.update({
  id: '/cloud-vps',
  path: '/cloud-vps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloud-vps': typeof CloudVpsRoute
  '/domains': typeof DomainsRoute
  '/hosting': typeof HostingRoute
  '/vps': typeof VpsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloud-vps': typeof CloudVpsRoute
  '/domains': typeof DomainsRoute
  '/hosting': typeof HostingRoute
  '/vps': typeof VpsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cloud-vps': typeof CloudVpsRoute
  '/domains': typeof DomainsRoute
  '/hosting': typeof HostingRoute
  '/vps': typeof VpsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cloud-vps' | '/domains' | '/hosting' | '/vps'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cloud-vps' | '/domains' | '/hosting' | '/vps'
  id: '__root__' | '/' | '/cloud-vps' | '/domains' | '/hosting' | '/vps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloudVpsRoute: typeof CloudVpsRoute
  DomainsRoute: typeof DomainsRoute
  HostingRoute: typeof HostingRoute
  VpsRoute: typeof VpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vps': {
      id: '/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof VpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-vps': {
      id: '/cloud-vps'
      path: '/cloud-vps'
      fullPath: '/cloud-vps'
      preLoaderRoute: typeof CloudVpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloudVpsRoute: CloudVpsRoute,
  DomainsRoute: DomainsRoute,
  HostingRoute: HostingRoute,
  VpsRoute: VpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
