/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XeonCloudVpsRouteImport } from './routes/xeon-cloud-vps'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as BdixCloudVpsRouteImport } from './routes/bdix-cloud-vps'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const XeonCloudVpsRoute = XeonCloudVpsRouteImport.update({
  id: '/xeon-cloud-vps',
  path: '/xeon-cloud-vps',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const BdixCloudVpsRoute = BdixCloudVpsRouteImport.update({
  id: '/bdix-cloud-vps',
  path: '/bdix-cloud-vps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/bdix-cloud-vps': typeof BdixCloudVpsRoute
  '/hosting': typeof HostingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/whois': typeof WhoisRoute
  '/xeon-cloud-vps': typeof XeonCloudVpsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/bdix-cloud-vps': typeof BdixCloudVpsRoute
  '/hosting': typeof HostingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/whois': typeof WhoisRoute
  '/xeon-cloud-vps': typeof XeonCloudVpsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/bdix-cloud-vps': typeof BdixCloudVpsRoute
  '/hosting': typeof HostingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/whois': typeof WhoisRoute
  '/xeon-cloud-vps': typeof XeonCloudVpsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/bdix-cloud-vps'
    | '/hosting'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/whois'
    | '/xeon-cloud-vps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/bdix-cloud-vps'
    | '/hosting'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/whois'
    | '/xeon-cloud-vps'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/bdix-cloud-vps'
    | '/hosting'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/whois'
    | '/xeon-cloud-vps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BdixCloudVpsRoute: typeof BdixCloudVpsRoute
  HostingRoute: typeof HostingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhoisRoute: typeof WhoisRoute
  XeonCloudVpsRoute: typeof XeonCloudVpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xeon-cloud-vps': {
      id: '/xeon-cloud-vps'
      path: '/xeon-cloud-vps'
      fullPath: '/xeon-cloud-vps'
      preLoaderRoute: typeof XeonCloudVpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bdix-cloud-vps': {
      id: '/bdix-cloud-vps'
      path: '/bdix-cloud-vps'
      fullPath: '/bdix-cloud-vps'
      preLoaderRoute: typeof BdixCloudVpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BdixCloudVpsRoute: BdixCloudVpsRoute,
  HostingRoute: HostingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhoisRoute: WhoisRoute,
  XeonCloudVpsRoute: XeonCloudVpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
